// Cities
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';

// Itineraries
export const FETCH_ITINERARIES_SUCCESS = 'FETCH_ITINERARIES_SUCCESS';
export const FETCH_ITINERARIES_REQUEST = 'FETCH_ITINERARIES_REQUEST';
export const FETCH_ITINERARIES_FAILURE = 'FETCH_ITINERARIES_FAILURE';

// Users
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const SET_USER_TOKEN = 'SET_USER_TOKEN';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';

export const FAVORITE_ITINERARY_SUCCESS = 'FAVORITE_ITINERARY_SUCCESS';
export const FAVORITE_ITINERARY_FAILURE = 'FAVORITE_ITINERARY_FAILURE';
export const UNFAVORITE_ITINERARY_SUCCESS = 'UNFAVORITE_ITINERARY_SUCCESS';
export const UNFAVORITE_ITINERARY_FAILURE = 'UNFAVORITE_ITINERARY_FAILURE';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';


